backend:
  name: github
  branch: main # اسم الفرع الرئيسي لمستودعك
  repo: amiraq1/nabd-ai-website # اسم مستودع GitHub

publish_mode: editorial_workflow # يفضل استخدام سير عمل التحرير للمراجعة قبل النشر

media_folder: "client/public/images" # المجلد الذي سيتم رفع الصور إليه
public_folder: "/images" # المسار العام للصور

collections:
  - name: "site_config" # اسم المجموعة (مجموعة واحدة للإعدادات العامة)
    label: "الإعدادات العامة"
    files:
      - file: "client/src/content/home.json" # الملف الذي سيتم تخزين بياناته
        label: "الصفحة الرئيسية"
        name: "home"
        fields:
          - label: "العنوان الرئيسي (نبض AI)"
            name: "main_title"
            widget: "string"
            default: "نبض AI"
          - label: "العنوان الفرعي"
            name: "sub_title"
            widget: "string"
            default: "صناعة المحتوى الرقمي بأسلوب عصري"
          - label: "الوصف"
            name: "description"
            widget: "text"
            default: "مرحباً، أنا عمار محمد. صانع محتوى، تقني متخصص في تبسيط المفاهيم المعقدة وتقديمها للجمهور العربي بأسلوب شيق ومبتكر"
          - label: "رقم زين كاش"
            name: "zaincash_number"
            widget: "string"
            default: "07830960059"
